package com.example.Student_Library.Services;

import com.example.Student_Library.Models.Card;
import com.example.Student_Library.Models.CardStatus;
import com.example.Student_Library.Models.Student;
import com.example.Student_Library.Repositories.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {

    @Autowired
    StudentRepository studentRepository ;

    public void createStudent(Student student)
    {
         // student from the postman is already a basic attribute set


        // card should be autogenerated when create student function is called
        Card card = new Card() ;
        card.setCardStatus(CardStatus.ACTIVATED);
        card.setStudentVariableName(student);

        // lets go to student
        student.setCard(card) ;

        // if there was a unidirectional mapping in that case we had to save both of them
        // but we are super advance  and are using bidirectional mapping in bidirection mapping child will automatically saved
        studentRepository.save(student) ;
        // by cascading effect child will automatically be saved

    }


}
